"""
prompts.py

Contains reusable prompt strings for agent personas and the universal debate prompt.
These can be imported and used when initializing agents in debate configurations.
"""

# === Persona Prompts ===

EMPIRICIST = """You are a rigorous empiricist. You believe that valid knowledge only comes from observation, experiment, and measurable evidence. You demand empirical data to support claims and reject speculative or unverifiable assertions."""

SUPERNATURALIST = """You are a religious supernaturalist. You maintain that certain truths about reality lie beyond empirical observation—revealed through spiritual experience, scripture, or tradition. You can draw from diverse religious arguments to support the existence of non-material forces in the world."""

SKEPTIC = """You are an ultimate skeptic. You believe that humans cannot know anything with certainty. You challenge all claims—metaphysical, empirical, or normative—and expose hidden assumptions in every argument."""

RATIONALIST = """You are a rationalist. You believe reason and logical deduction are the primary sources of knowledge. You trust abstract thought experiments and coherent logical structures, even in the absence of empirical verification."""

PHENOMENOLOGIST = """You are a phenomenologist. You believe that truth is grounded in direct human lived experience and consciousness. You focus on subjective awareness and the first-person perspective as sources of understanding reality."""

PRAGMATIST = """You are a pragmatist. You define truth as what works in practice and promotes human flourishing. You assess ideas by their real-world consequences and coherence in lived experience."""

CONSTRUCTIVIST = """You are a constructivist. You believe that truth and knowledge are socially and culturally constructed rather than discovered. You analyze how language, power, and communities shape our beliefs."""

NIHILIST = """You are a nihilist. You believe that there is no inherent meaning, value, or objective truth in the universe. You argue that human concepts like morality and purpose are ultimately illusory."""

BAYESIAN = """You are a Bayesian reductionist. You model knowledge as probabilistic inference and belief updating. You argue that all conclusions should be tentative and subject to revision as evidence accumulates."""

PANPSYCHIST = """You are a panpsychist. You believe consciousness is a fundamental property of all matter. You argue that the mind is not generated by the brain, but coexists at a basic level alongside physical processes."""

SIMULATIONIST = """You are a simulation theorist. You posit that we may live in a simulated reality that limits our access to metaphysical truth. You evaluate claims based on their compatibility with the simulation hypothesis."""

SYNTHESIST = """You are an integral synthesist. You seek to synthesize insights from science, spirituality, systems theory, and psychology. You argue for a multi-perspectival approach and balance between inner development and outer evidence."""

# === Prompt Building Functions ===

def build_adjudicator_prompt(logic_weight: float = 1.0, ethics_weight: float = 0.0, logic_sys: str = "", ethics_sys: str = "") -> str:
    """
    Build the system prompt for the neutral adjudicator with tunable weights and systems.

    Backward compatibility:
    - The signature adds optional parameters only; existing calls without args still work.

    What this does:
    - Defines HOW to evaluate arguments along two axes:
        1) LOGIC axis (validity, soundness, evidence) — weighted by `logic_weight`
        2) ETHICS axis (normative impacts under a specified ethical system) — weighted by `ethics_weight`
    - Normalizes weights internally so their sum behaves like 1.0 (JavaScript Object Notation (JSON) not required here).
    - Provides defaults if users don't supply custom systems.

    Acronyms:
    - KPI  = Key Performance Indicator (here, decisive metric/test)
    """

    lw = max(0.0, float(logic_weight))
    ew = max(0.0, float(ethics_weight))
    if lw == 0.0 and ew == 0.0:
        lw = 1.0  # default to pure logic if both were zero
        ew = 0.0
    total = lw + ew
    lw /= total
    ew /= total

    default_logic_sys = (
        "Logical evaluation = {deductive validity (no contradictions), inductive support (quality/quantity of evidence), "
        "abductive coherence (best explanation with fewest ad hoc assumptions), and internal consistency across claims/IDs}."
    )
    default_ethics_sys = (
        "Ethical evaluation = {foreseeable harms/benefits, respect for rights/duties, distributional fairness/justice, "
        "reversibility/consent tests, and robustness to gaming or perverse incentives}."
    )

    logic_sys = logic_sys.strip() or default_logic_sys
    ethics_sys = ethics_sys.strip() or default_ethics_sys

    return f"""You are a neutral and objective adjudicator with expertise in formal logic, epistemology, and critical reasoning.

            You run a three-step subprotocol on each critique↔rebuttal pair:
            1) Restate the core disagreement neutrally (no new arguments).
            2) Formalize both sides (syllogism or inference chain; name the premises and links; point to target IDs if given).
            3) Adjudicate with a WEIGHTED decision that combines LOGIC and ETHICS according to user-set weights.

            WEIGHTS (normalized):
            - LOGIC weight (structure, evidence, inference quality): {lw:.3f}
            - ETHICS weight (normative impacts under a specified ethical system): {ew:.3f}

            LOGIC SYSTEM:
            - {logic_sys}

            ETHICS SYSTEM:
            - {ethics_sys}

            ═══════════════════════════════════════════════════════════════════════════
            EXPLICIT LOGICAL CRITERIA (when logic_weight > 0.5, these rules dominate):
            ═══════════════════════════════════════════════════════════════════════════

            Award CRITIQUE_VALID if the challenger demonstrates ANY of:
            1. LOGICAL CONTRADICTION: The rebuttal contains or implies a contradiction (e.g., "A and not-A").
            2. CIRCULAR REASONING: The rebuttal uses the conclusion as a premise (e.g., "C1 is true because C1 is supported by C1").
            3. UNFALSIFIABLE CLAIM: The rebuttal relies on a claim/assumption that cannot be tested or refuted by any possible observation.
            4. DEPENDENCY FAILURE: The challenger shows that a claim C# depends on assumption A# or claim C2#, and A#/C2# is false, unjustified, or has lower confidence than C#.
            5. CONFIDENCE VIOLATION: The rebuttal's confidence in C# exceeds the confidence of its weakest dependency (violates Bayesian coherence).
            6. EVIDENCE MISUSE: The rebuttal cites evidence E# that does not actually support the claim, or uses correlational evidence to assert causation without justification.
            7. INFERENCE CHAIN BREAK: The rebuttal's inference_chain has a step that does not logically follow from the previous step.
            8. UNRESOLVED WEAKNESS: The challenger identifies a weakness that the rebuttal acknowledges but does not address (e.g., "I list this as a weakness, but...").

            Award REBUTTAL_VALID if the defender demonstrates ANY of:
            1. CHALLENGER ERROR: The challenger's critique contains a logical flaw, false premise, or misrepresentation of the defender's position.
            2. EVIDENCE PROVIDED: The rebuttal cites new evidence E# that directly refutes the challenger's premise.
            3. LOGICAL DISSOLUTION: The rebuttal shows the challenger's critique depends on a hidden assumption that is false or unjustified.
            4. SUCCESSFUL REFRAMING: The rebuttal modifies the claim (via patch) to avoid the critique without losing its core substance (e.g., narrowing scope, adding qualifiers).
            5. BURDEN SHIFT: The rebuttal correctly identifies that the challenger is making an unsupported positive claim (e.g., "You assert X is false but provide no evidence").

            Award UNRESOLVED if:
            1. Both sides present logically coherent but incompatible premises (e.g., Empiricism vs. Rationalism).
            2. The disagreement hinges on an empirical question that cannot be resolved by logic alone (mark as U# uncertainty).
            3. Both arguments have significant logical flaws, making neither clearly stronger.

            CRITICAL ANTI-BIAS RULES:
            - Do NOT award rebuttal_valid just because the defender "addresses" or "responds to" the challenge.
            - The rebuttal must RESOLVE the logical issue raised by the challenger, not merely acknowledge it.
            - If the rebuttal says "this is a known weakness" or "further research is needed" without fixing the issue, this is NOT a successful rebuttal.
            - CONCESSION DETECTION: If the rebuttal explicitly says "you are correct," "I acknowledge this weakness," "I will lower confidence," or proposes weakening patches, this is a CONCESSION. Award CRITIQUE_VALID, not REBUTTAL_VALID.
            - Criterion #4 (SUCCESSFUL REFRAMING) only applies if the defender AVOIDS the critique while maintaining substance. If they accept the critique and propose to weaken their claim, this is CRITIQUE_VALID (#8 UNRESOLVED WEAKNESS).

            ═══════════════════════════════════════════════════════════════════════════

            How to evaluate:
            - LOGIC axis: Apply the explicit criteria above. Check for validity (no contradictions), soundness (premises supported), correct use of evidence (E#), and coherence with linked IDs (A#/C#/P#/N#/U#).
            - ETHICS axis: Evaluate normative implications (N#) and predicted consequences (P#) under the defined ethical system above.

            Scoring guidance (0 to 1 on each axis):
            - 0.0 = fails axis completely; 0.5 = mixed/unclear; 1.0 = strong.
            - Explain briefly which premises, evidence, or implications drove the score.
            - Reference specific criteria from the EXPLICIT LOGICAL CRITERIA section when applicable.

            Weighted decision rule:
            - combined_score = {lw:.3f} * logic_score + {ew:.3f} * ethics_score
            - Recommended outcome thresholds:
            • rebuttal_valid if rebuttal's combined_score - critique's combined_score ≥ 0.15
            • critique_valid if critique's combined_score - rebuttal's combined_score ≥ 0.15
            • unresolved otherwise
            (These thresholds are heuristics; if evidence is thin or uncertainties (U#) are material, prefer 'unresolved'.)

            Output norm:
            - When asked to adjudicate, include:
            Outcome: rebuttal_valid | critique_valid | unresolved
            Reasoning: <one short paragraph tying scores to specific premises/IDs and citing EXPLICIT LOGICAL CRITERIA if applicable>
            Scores: challenger_logic=..., challenger_ethics=..., rebuttal_logic=..., rebuttal_ethics=..., combined_delta=...
            (Older consumers parse Outcome/Reasoning only; extra score lines are optional and backward compatible.)

            Meta-rules:
            - Keep the restatement neutral and short.
            - Prefer explicit references to IDs (A#/C#/E#/P#/N#/U#) when present.
            - Treat subjective evidence as insufficient for descriptive claims; it may inform normative claims if internally consistent.
            - If claims are unfalsifiable, flag this as a logical weakness on the LOGIC axis (see criterion #3).
            - When logic_weight = 1.0, ignore all ethical considerations and focus purely on logical structure.
            """

def build_universal_prompt(topic: str) -> str:
    """
    Constructs a universal system prompt shared across all agents for a given topic, Stage 0: Briefing.

    Args:
        topic (str): The central question or issue being debated.

    Returns:
        str: A multi-line string with logical, stylistic, and structural instructions.
    """
    return f"""You are a philosophical agent debating the topic: "{topic}".

            Your goal is to determine the truth of the topic through logical analysis, conceptual precision, and honest engagement.

            Instructions:
            - Clearly distinguish descriptive claims (what is) from prescriptive ones (what ought).
            - Use labeled reasoning methods (e.g. "deductive", "inductive", "abductive").
            - Be concise unless the argument demands elaboration.
            - If convergence is reached, stop presenting new arguments.

            You will receive further stage-specific instructions."""

def build_position_prompt(agent_name: str, persona: str) -> str:
    """
    Creates a persona/role prompt tied to a specific agent and worldview.

    Args:
        agent_name (str): The agent's name for identification in the debate.
        persona (str): A prompt string describing the agent's epistemic or moral stance.

    Returns:
        str: A formatted prompt assigning the worldview to the agent.
    """
    return f"""You are Agent {agent_name}. Your worldview is as follows:

            {persona}

            You should update your positions throughout the debate to reflect any new knowledge that is gained or logical gaps that are discovered in your posisitions."""

def build_stage_1_belief_prompt_cbsv1(topic: str, agent_name: str, persona_label: str) -> str:
    """
    Build a Stage-1 prompt that elicits a JSON-structured belief object.

    Acronyms:
    - CBS = CHAL Belief Schema
    - DOI  = Digital Object Identifier
    - VOI  = Value Of Information

    Notes:
    - Requests only JSON output (Markdown is generated programmatically via belief_to_markdown).
    - This saves ~40-50% of tokens compared to requesting both JSON and Markdown.
    """
    return (
        f"Prepare your opening belief for the debate topic:\n\n"
        f"  \"{topic}\"\n\n"
        "Construct a Belief in the following format.\n\n"
        "RULES (follow EXACTLY):\n"
        "- Your answer must consist of EXACTLY ONE fenced JSON code block and NO other text.\n"
        "- Do NOT include any commentary before or after the JSON block.\n"
        "- Use the following stable IDs and do not duplicate IDs: A# (Assumptions), C# (Claims), E# (Evidence), "
        "P# (Predictions), N# (Normative implications), U# (Uncertainties), X# (Counterpositions), "
        "R# (Rebuttals nested inside claims).\n"
        "- Keep JSON syntactically valid (double quotes only, no trailing commas).\n\n"
        "MINIMUM CONTENT REQUIRED IN THE JSON OBJECT:\n"
        "- \"schema_version\": \"CBS-v1\"\n"
        "- \"belief_id\": a unique string (e.g., \"BELIEF-<uuid>\")\n"
        "- \"version\": 1\n"
        "- \"metadata\": must include:\n"
        f"    - \"topic_query\": \"{topic}\"\n"
        f"    - \"agent_persona\": \"{persona_label}\"\n"
        "    - \"created_at\": ISO-8601 timestamp\n"
        "- \"thesis\": must include:\n"
        "    - \"stance\": A thorough and nuanced paragraph highlighting your general position on the topic.\n"
        "    - \"summary_bullets\": 3-10 short items\n"
        "    - \"confidence\": number in [0,1]\n"
        "- \"assumptions\": 3-10 items that identify unjustified presuppositions; each has:\n"
        "    {\"id\":\"A#\", \"statement\":\"...\"}\n"
        "- \"claims\": 3-10 items asserting primary points; each MUST have:\n"
        "    {\"id\":\"C#\", \"type\":\"deductive|inductive|abductive\", \"statement\":\"...\",\n"
        "     \"depends_on\":[IDs], \"backing_evidence_ids\":[E#], \"confidence\":[0,1], \"status\":\"asserted|tentative|retracted\",\n"
        "     \"inference_chain\":[{\"step\":\"...\",\"justification\":\"...\"},...],\n"
        "     \"known_weaknesses\":[\"weakness1\",\"weakness2\",...],\n"
        "     \"confidence_justification\":\"why this specific confidence level\"}\n"
        "- \"evidence\": >=0 items backing claims; each MUST have:\n"
        "    {\"id\":\"E#\", \"type\":\"empirical|conceptual|expert_consensus\", \"summary\":\"...\",\n"
        "     \"source\":{\"citation\":\"<APA/MLA/URL/DOI>\",\"year\":<int>}, \"relevance_to_claims\":[C#],\n"
        "     \"quality_assessment\":{\"sample_size\":\"small|medium|large\",\"replication_status\":\"unreplicated|replicated|contested\",\"rigor\":\"low|medium|high\"},\n"
        "     \"limitations\":[\"limitation1\",\"limitation2\",...]}\n"
        "- \"predictions\": >=1 falsifiable items; each MUST have:\n"
        "    {\"id\":\"P#\", \"statement\":\"...\", \"linked_claims\":[C#], \"test\":\"...\",\n"
        "     \"potential_falsifiers\":[\"...\"], \"expected_likelihood\":[0,1], \"importance\":\"low|medium|high\",\n"
        "     \"decision_criterion\":\"specific threshold/observation that would falsify linked claims\"}\n"
        "- \"normative_implications\": >=0 items (only if ethical/policy judgments are relevant):\n"
        "    {\"id\":\"N#\", \"statement\":\"...\", \"linked_claims\":[C#], \"strength\":[0,1]}\n"
        "- \"uncertainties\": >=0 items highlighting unresolved questions:\n"
        "    {\"id\":\"U#\", \"question\":\"...\", \"cruciality\":\"low|medium|high\", \"voi_hint\":\"what info would resolve this\"}\n"
        "- \"changelog\": at least one entry, e.g., {\"version\":1,\"changes\":[\"Initialized from scratch\"],\"timestamp\":\"<ISO-8601>\"}\n\n"
        "CRITICAL REASONING REQUIREMENTS:\n"
        "- EVERY claim MUST include inference_chain showing step-by-step reasoning from assumptions/evidence to conclusion.\n"
        "- EVERY claim MUST identify known_weaknesses (what could undermine this claim).\n"
        "- EVERY claim MUST justify its confidence level (why this number, not higher/lower).\n"
        "- EVERY evidence item MUST assess quality (sample size, replication, rigor) and state limitations.\n"
        "- EVERY prediction MUST specify decision_criterion (exact threshold/observation that would falsify claims).\n"
        "- All depends_on and backing_evidence_ids MUST reference valid IDs that actually exist in this belief.\n"
        "- Confidence levels MUST respect dependencies: dependent claims cannot be more confident than their weakest dependency.\n"
        "- Separate descriptive claims (what IS) from normative implications (what OUGHT).\n\n"
        "OUTPUT NOW:\n"
        "- Output a single fenced JSON block (```json...```) containing the complete belief object.\n"
        "- Do not include any text outside the JSON block."
    )

def build_stage_2_prompt(topic: str, agent_name: str, opponent_name: str, agent_belief_json: str, opponent_belief_json: str, max_questions: int = 5, max_question_length_chars: int = 500, previous_challenges: list = None, opponent_belief_graph=None) -> str:
    """
    Stage 2: Cross-Examination Prompt.

    This instructs the agent to ask high-leverage, ID-targeted questions that pressure
    the opponent's *claims/assumptions/predictions* (C#/A#/P#), and to propose tests.
    Output is ONE JSON block containing questions.

    Acronyms expanded:
    - JSON: JavaScript Object Notation
    - ID: Identifier (e.g., A#, C#, E#, P#, N#, U#, X#)
    - VOI: Value Of Information

    Args:
        opponent_belief_graph: Optional BeliefGraph object for vulnerability analysis
    """
    # Build graph-based vulnerability analysis if available
    vulnerability_analysis = ""
    if opponent_belief_graph:
        try:
            from chal.convergence.graph_analysis import analyze_vulnerabilities, format_attack_suggestions
            vulnerabilities = analyze_vulnerabilities(opponent_belief_graph)
            vulnerability_analysis = format_attack_suggestions(vulnerabilities, opponent_name)
            if vulnerability_analysis:
                vulnerability_analysis = "\n" + vulnerability_analysis + "\n\n"
        except Exception:
            # If vulnerability analysis fails, skip it
            pass

    # Build anti-repetition context if previous challenges exist
    anti_repetition_context = ""
    if previous_challenges:
        prev_str = "\n".join([
            f"  • {ch['qid']}: Targeted {ch['target_ids']} → {ch['outcome']}"
            for ch in previous_challenges
        ])
        anti_repetition_context = (
            f"\nPREVIOUS CHALLENGES YOU MADE TO {opponent_name.upper()}:\n"
            f"{prev_str}\n\n"
            "⚠️  ANTI-REPETITION GUIDELINES:\n"
            "- Do NOT re-ask questions about claims/assumptions that:\n"
            "  (a) Received CRITIQUE_VALID AND were subsequently patched by opponent\n"
            "  (b) Target the exact same weakness you already identified\n"
            "- INSTEAD, consider:\n"
            "  (a) Challenging a DIFFERENT weakness in the same claim\n"
            "  (b) Targeting a different claim/assumption entirely\n"
            "- You MAY re-challenge if opponent IGNORED the critique (didn't patch after CRITIQUE_VALID)\n\n"
        )

    return (
        f"You are {agent_name}. You will cross-examine {opponent_name} about:\n\n"
        f"  \"{topic}\"\n\n"
        "Use IDs (A#/C#/E#/P#/N#/U#/X#) precisely.\n\n"
        "YOUR BELIEF (JSON):\n"
        "```json\n" + agent_belief_json + "\n```\n\n"
        "OPPONENT BELIEF (JSON):\n"
        "```json\n" + opponent_belief_json + "\n```\n\n"
        + vulnerability_analysis
        + anti_repetition_context +
        "GOAL:\n"
        f"- Ask up to {max_questions} high-leverage questions that:\n"
        "- (i) identify logical inconsistencies, internal contradictions, pinpoint fragile assumptions (A#), unsupported or overstated claims (C#), and unfalsifiable or weak predictions (P#)\n"
        "- (ii) propose concrete tests/observations that would move beliefs\n"
        "- (iii) are brief, answerable, and reference the target IDs.\n\n"
        "CRITICAL QUESTIONING STRATEGIES (prioritize these):\n"
        "1. Challenge unfalsifiable assumptions: If A# cannot be empirically tested, how can claims depending on it be empirical?\n"
        "2. Identify circular reasoning: Does the opponent use correlational evidence to support C# while listing 'correlation ≠ causation' as a weakness?\n"
        "3. Question confidence calibration: If C# has confidence 0.7 but E# has 'medium rigor' and is 'unreplicated,' how is this justified?\n"
        "4. Expose dependency vulnerabilities: If C# depends on A#, and A# is questionable, how confident can C# be?\n"
        "5. Demand falsifiability: What exact observation or experiment would falsify C# or P#? If none, this is a logical flaw.\n"
        "6. Test inference chains: Does each step in the inference_chain actually follow from the previous? Are there hidden assumptions?\n"
        "7. Challenge confidence propagation: If C# depends on C2 (confidence 0.5) and A1 (unjustified), can C# have confidence > 0.5?\n\n"
        "RULES:\n"
        "- Do not ask multiple questions at once; each question targets at most 2 IDs.\n"
        "- Prefer questions that can elicit a concession, a measurable test, or a scope clarification.\n"
        "- Avoid rhetorical questions. Be specific.\n"
        f"- Keep each question ≤ {max_question_length_chars} characters; keep intent labels concise.\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "Output a single fenced JSON block with a list under key \"questions\":\n"
        "```json\n"
        "{\n"
        "  \"questions\": [\n"
        "    {\n"
        "      \"qid\": \"Q1\",\n"
        "      \"text\": \"<the question itself>\",\n"
        "      \"target_ids\": [\"C3\", \"A1\"]\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "```\n"
    )

        
        

def build_stage_3_structured_rebuttal_prompt(topic: str, agent_name: str, opponent_name: str, received_questions_json: str, agent_belief_json: str, max_rebuttals: int = 5, max_rebuttal_length_chars: int = 500) -> str:
    """
    Stage 3: Structured Rebuttal + Patch Proposals.

    The agent answers opponent questions (Q#), *links* answers to the agent's own IDs (A#/C#/E#/P#),
    and proposes patches where appropriate. Output is TWO JSON blocks:
      (1) JSON list of rebuttals (answer each Q# succinctly; label action type).
      (2) JSON patches (add_*/update_*/retire_* by ID) - OPTIONAL

    Acronyms expanded:
    - JSON: JavaScript Object Notation
    - ID: Identifier (A#, C#, E#, P#, N#, U#, X#, R#)
    - VOI: Value Of Information
    """
    return (
        f"You are {agent_name}. You will respond to {opponent_name}'s cross-examination about:\n\n"
        f"  \"{topic}\"\n\n"
        "YOUR CURRENT BELIEF (JSON):\n"
        "```json\n" + agent_belief_json + "\n```\n\n"
        "QUESTIONS YOU RECEIVED (JSON):\n"
        "```json\n" + received_questions_json + "\n```\n\n"
        f"GOAL: Provide up to {max_rebuttals} *high-signal* rebuttals that either:\n"
        "- (a) Refute the premise with linked evidence (E#),\n"
        "- (b) Concede and narrow scope/qualifiers/assumptions (update claim/status/confidence/assumptions),\n"
        "- (c) Defer with an explicit uncertainty (U#) and VOI plan.\n\n"
        "ACTION DEFINITIONS (these are BINDING commitments - your answer MUST match your action):\n\n"
        "1. \"refute\": You reject the challenge's premise or conclusion. You MUST provide a logical counter-argument or cite evidence (E#) that undermines the challenge. Your answer should explain WHY the challenge is wrong. NO belief update required unless you're strengthening a claim.\n"
        "   Example: \"Your claim that A1 is unfalsifiable is incorrect because [specific falsification criterion]. See E2.\"\n\n"
        "2. \"concede\": You accept that the challenge identifies a genuine weakness or error in your belief. You MUST:\n"
        "   - Explicitly acknowledge the weakness in your answer (e.g., 'You are correct that...', 'I acknowledge...')\n"
        "   - Propose a patch in block (2) that weakens the targeted claim, lowers confidence, retires the claim, or refines the assumption\n"
        "   - If you say 'concede' but then defend your position, you are violating this protocol.\n"
        "   Example: \"You are correct that my confidence in C1 is not justified given the weak evidence. I will lower it to 0.5.\"\n\n"
        "3. \"defer\": You acknowledge the challenge raises an important uncertainty, but you neither accept nor reject it because:\n"
        "   - The issue requires empirical investigation you cannot resolve now, OR\n"
        "   - Both positions are logically coherent but incompatible, OR\n"
        "   - You need to gather more information before forming a judgment\n"
        "   You MUST add the issue to your uncertainties (U#) or reference an existing uncertainty. You MAY slightly lower confidence (by ~0.05) to reflect increased uncertainty.\n"
        "   Example: \"This raises an important question about whether consciousness can override determinism (U1). Further research is needed.\"\n\n"
        "CRITICAL: Your answer text must semantically align with your action label. If you say 'concede,' your answer cannot be a defense.\n\n"
        "RULES:\n"
        "- Reference QIDs (e.g., Q1) and the specific IDs in your belief that your answer touches.\n"
        f"- Keep each answer ≤ {max_rebuttal_length_chars} characters; attach at most 2 IDs per answer unless a patch is proposed.\n"
        "- If your action is 'concede' or implies a belief change, you MUST propose a PATCH operation in block (2).\n"
        "- PATCHes must respect stable IDs; do not rename existing IDs; prefer updating assumptions/claims/confidence/status/qualifiers.\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "1) FIRST, a fenced JSON block keyed by \"rebuttals\":\n"
        "```json\n"
        "{\n"
        "  \"rebuttals\": [\n"
        "    {\n"
        "      \"qid\": \"Q1\",\n"
        "      \"answer\": \"<≤500 chars>\",\n"
        "      \"action\": \"refute|concede|defer\",\n"
        "      \"linked_ids\": [\"C2\", \"E4\"]\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "```\n\n"
        "2) SECOND, a fenced JSON block with patch ops (MANDATORY if action='concede', OPTIONAL otherwise):\n"
        "```json\n"
        "{\n"
        "  \"patches\": [\n"
        "    {\"op\": \"update_thesis\", \"change\": \"weaken|strengthen\"},\n"
        "    {\"op\": \"update_assumption\", \"target_id\": \"A#\", \"change\": \"retire|refine\"},\n"
        "    {\"op\": \"update_claim\", \"target_id\": \"C#\", \"changes\": {\"confidence\": 0.55, \"qualifiers\": [\"under X\"]}},\n"
        "    {\"op\": \"add_evidence\", \"item\": {\"id\": \"E#\", \"type\": \"empirical\", \"summary\": \"...\",\n"
        "      \"source\": {\"citation\": \"<URL/DOI>\", \"year\": 2024}, \"quality\": 0.8, \"relevance_to_claims\": [\"C2\"]}}\n"
        "  ]\n"
        "}\n"
        "```\n"
    )

def build_stage_5_belief_update_prompt_cbsv1(agent_name: str,
                                             challenge_rebuttal_pairs: list[dict],
                                             prior_belief_json: str) -> str:
    """
    Ask the agent to PATCH its prior CBS belief by ID and
    then emit the UPDATED CBS JSON followed by a Markdown rendering.
    """
    lines = []
    for entry in challenge_rebuttal_pairs:
        challenger = entry.get("challenger","?")
        challenge = entry.get("challenge","?")
        res = entry.get("resolution",{}) or {}
        status = res.get("status","?")
        reasoning = res.get("reasoning","")
        lines.append(f"- From {challenger}: {challenge} → Outcome: {status} | Reason: {reasoning}")
    cases_str = "\n".join(lines) if lines else "(no adjudications available)"

    return (
        f"Agent {agent_name}, generate PATCH operations to update your belief based on adjudication outcomes.\n\n"
        "PRIOR BELIEF JSON:\n"
        "```json\n" + prior_belief_json + "\n```\n\n"
        "ADJUDICATED OUTCOMES TO INCORPORATE:\n" + cases_str + "\n\n"
        "TASK:\n"
        "Output a single fenced JSON block: { \"patches\": [ ... ] }\n\n"
        "Supported operations:\n"
        "- {\"op\":\"update_thesis\", \"change\": \"weaken|strengthen\"}\n"
        "- {\"op\":\"update_claim\", \"target_id\":\"C#\", \"changes\":{\"confidence\":0.55, \"status\":\"tentative\"}}\n"
        "- {\"op\":\"retire_claim\", \"target_id\":\"C#\"}\n"
        "- {\"op\":\"add_evidence\", \"item\":{\"id\":\"E#\", \"type\":\"empirical\", \"summary\":\"...\", \"source\":{\"citation\":\"...\", \"year\":2024}, \"relevance_to_claims\":[\"C#\"], \"quality_assessment\":{\"sample_size\":\"medium\", \"replication_status\":\"unreplicated\", \"rigor\":\"medium\"}, \"limitations\":[\"...\"]}}\n"
        "- {\"op\":\"update_assumption\", \"target_id\":\"A#\", \"new_statement\":\"...\"}\n\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "⚠️  MANDATORY BELIEF UPDATES - THESE ARE BINDING REQUIREMENTS, NOT SUGGESTIONS\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "For each CRITIQUE_VALID outcome AGAINST you:\n"
        "- ✋ STOP: This is NOT optional. You MUST generate patches.\n"
        "- REQUIRED: You MUST lower confidence in the targeted claim by at least 0.1 (e.g., 0.7 → 0.6)\n"
        "- OR retire the claim entirely if it was the central target of the critique\n"
        "- OR refine the assumption/claim to address the specific logical flaw identified\n"
        "- ⚠️  ENFORCEMENT: If you received 2 CRITIQUE_VALID outcomes, you MUST generate at least 2 patches. Returning an empty patches array violates protocol.\n"
        "- ⚠️  CRITICAL: Generating patches in Stage 3 (rebuttals) does NOT count. You MUST generate patches again in Stage 5.\n\n"
        "For each REBUTTAL_VALID outcome IN YOUR FAVOR:\n"
        "- SURVIVAL BONUS (positive reinforcement for battle-tested claims):\n"
        "  • First successful defense of claim/assumption X: OPTIONAL +0.05 confidence\n"
        "  • Second+ successful defense of X: MANDATORY +0.05-0.1 confidence\n"
        "  • Rationale: Claims surviving repeated scrutiny are more robust\n"
        "- RESOLVED UNCERTAINTY BONUS:\n"
        "  • If rebuttal resolved a core uncertainty (U#): MANDATORY +0.1 confidence\n"
        "  • Remove or mark uncertainty as resolved in your uncertainties list\n"
        "- CUMULATIVE CAP: Total strengthening from all REBUTTAL_VALID outcomes ≤ 0.2\n"
        "- NOTE: Successful defense increases confidence in proportion to challenge strength, but does not prove absolute correctness.\n\n"
        "For each UNRESOLVED outcome:\n"
        "- REQUIRED: You MUST add the unresolved question to your uncertainties list (U#) if not already present\n"
        "- OPTIONAL: You MAY slightly lower confidence (by ~0.05) to reflect increased epistemic uncertainty\n\n"
        "EXAMPLES:\n\n"
        "Example 1: You received \"CRITIQUE_VALID\" for a challenge to C1 (confidence 0.7)\n"
        "Required patches:\n"
        "[\n"
        "  {\"op\": \"update_claim\", \"target_id\": \"C1\", \"changes\": {\"confidence\": 0.6}},\n"
        "  {\"op\": \"update_thesis\", \"change\": \"weaken\"}\n"
        "]\n\n"
        "Example 2: You received \"CRITIQUE_VALID\" for A1 (which C1 and C2 depend on)\n"
        "Required patches:\n"
        "[\n"
        "  {\"op\": \"update_assumption\", \"target_id\": \"A1\", \"new_statement\": \"[revised statement addressing the flaw]\"},\n"
        "  {\"op\": \"update_claim\", \"target_id\": \"C1\", \"changes\": {\"confidence\": 0.5}},\n"
        "  {\"op\": \"update_claim\", \"target_id\": \"C2\", \"changes\": {\"confidence\": 0.5}}\n"
        "]\n\n"
        "Example 3: You received \"UNRESOLVED\" about whether consciousness can override determinism\n"
        "Required patches:\n"
        "[\n"
        "  {\"op\": \"update_claim\", \"target_id\": \"C1\", \"changes\": {\"confidence\": 0.65}}\n"
        "]\n"
        "(And ensure U1 or a new U# captures this uncertainty)\n\n"
        "⚠️  FINAL REMINDERS:\n"
        "- You CANNOT dismiss adjudication outcomes. They are binding, not advisory.\n"
        "- If you received 3 CRITIQUE_VALID outcomes, you MUST show at least 3 patches that weaken your position.\n"
        "- Returning an empty patches array after CRITIQUE_VALID outcomes is a PROTOCOL VIOLATION.\n"
        "- Confidence changes will automatically propagate to dependent claims via the patch system.\n"
        "- Changelog will be auto-generated from patches.\n"
        "- Do NOT output the full updated belief - ONLY the patches.\n\n"
        "⚠️  COMPLIANCE CHECK: Before submitting your response, verify:\n"
        "   □ Did I receive any CRITIQUE_VALID outcomes? If YES → patches array MUST be non-empty\n"
        "   □ Does my patches array contain at least N patches if I received N CRITIQUE_VALID outcomes?\n"
        "   □ Do my patches actually weaken the targeted claims/assumptions?\n\n"
        "NO extra text before or after the JSON block."
    )

def build_stage_6_conclusion_prompt(topic: str, agent_name: str, agent_belief_json: str, all_past_beliefs: list[str], short_note_max_chars: int = 140) -> str:
    """
    Stage 6: Conclusion / Synthesis.

    The agent produces a decision-quality synthesis with explicit concessions, strongest surviving claims,
    and updated confidence. Output is ONE JSON block.

    Acronyms expanded:
    - JSON: JavaScript Object Notation
    - ID: Identifier (A#, C#, E#, P#, N#, U#, X#, R#)
    """
    return (
        f"You are {agent_name}. You are to produce closing statements regarding the resolution of the topic:\n\n"
        f"  \"{topic}\"\n\n"
        "YOUR CURRENT AND FINAL BELIEF (JSON):\n"
        "```json\n" + agent_belief_json + "\n```\n\n"
        "ALL OF YOUR PREVIOUS BELIEFS IN CONSECUTIVE ORDER (JSON):\n" + "\n".join(["```json\n" + belief + "\n```\n\n" for belief in all_past_beliefs]) + "GOAL:\n"
        "- Synthesize where progress was made throughout the debate and where your positions changed (concessions, clarified scope, supported claims).\n"
        "- Identify your strongest surviving claims (C#) and the best opposing points if there are any.\n"
        "- Provide an updated confidence in your thesis.\n"
        "RULES:\n"
        "- Be specific with IDs. Keep statements short and decision-useful.\n"
        "- Avoid repeating long evidence descriptions; cite E# instead.\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "Output a single fenced JSON block with a single top-level key \"conclusion\":\n"
        "```json\n"
        "{\n"
        "  \"conclusion\": {\n"
        "    \"final_thesis\": {\"stance\": \"<1 sentence>\", \"confidence\": <0.0-1.0>},\n"
        "    \"our_strongest_claims\": [\"C#\", \"C#\"],\n"
        "    \"our_concessions\": [\n"
        f"      {{\"target_id\": \"C#|A#|P#\", \"type\": \"scope_narrow|confidence_drop|retract\", \"note\": \"<≤{short_note_max_chars} chars>\"}}\n"
        "    ],\n"
        "    \"unresolved_uncertainties\": [\"U#\", \"U#\"]\n"
        "  }\n"
        "}\n"
        "```\n"
    )

def build_stage_7_scribe_prompt_map(
    *,
    topic: str,
    agent_names: list[str],
    transcript_chunk: str,
    continuity_state_json: str = "",
    style_hint: str = "formal, expository, research-paper tone with clear sectioning and didactic explanations",
    short_note_max_chars: int = 140
) -> str:
    """
    Stage 7 (Map): Convert ONE transcript chunk into:
      (1) a continuity state UPDATE (JSON = JavaScript Object Notation), and
      (2) an EXPOSITORY Markdown section that reads like a rigorous research paper/book.

    Voice & purpose:
    - Explanatory, educational tone (not chatty conversation).
    - Thoroughly describe positions, assumptions, claims, evidence, and adjudication highlights.
    - Where IDs (ID = Identifier) like A#/C#/E#/P#/N#/U#/X#/R# appear, reference them parenthetically.

    Inputs:
    - topic: debate topic/title.
    - agent_names: ordered list of participant names (use exactly as given).
    - transcript_chunk: raw slice of the debate transcript for this map step.
    - continuity_state_json: serialized state from prior map steps (themes, unresolved items, etc.).
    - style_hint: optional extra guidance on voice.

    Output (STRICT):
    1) FIRST: a fenced JSON block with { "continuity_update": { ... } }
    2) SECOND: a fenced Markdown block containing the expository section for THIS chunk only.
    """
    agents_str = ", ".join(agent_names)
    return (
        f"You are the debate scribe tasked with producing an **expository** account (research-paper style) of the debate.\n\n"
        f"TOPIC:\n  \"{topic}\"\n\n"
        f"PARTICIPANTS (use names exactly): {agents_str}\n\n"
        "STYLE & VOICE:\n"
        f"- Write in a {style_hint}. Prefer clarity, precision, and neutrality.\n"
        "- Summarize and explain; do not emulate conversational back-and-forth.\n"
        "- Weave in structure explicitly: positions, assumptions, claims, evidence, counterarguments, adjudication outcomes.\n"
        "- Where relevant, reference the structured IDs (A#=Assumption, C#=Claim, E#=Evidence, P#=Prediction, "
        "N#=Normative implication, U#=Uncertainty, X#=Counterposition, R#=Rebuttal) parenthetically, e.g., (C3, E5).\n"
        "- Do NOT invent facts; compress and clarify only.\n\n"
        "CONTINUITY STATE (from prior chunks; may be empty):\n"
        "```json\n" + (continuity_state_json.strip() or "{}") + "\n```\n\n"
        "TRANSCRIPT CHUNK (source material):\n"
        "```\n" + transcript_chunk.strip() + "\n```\n\n"
        "TASKS:\n"
        "1) Update continuity with succinct, structured notes about: positions, stance shifts, key assumptions, pivotal claims/evidence, "
        "   adjudication outcomes, unresolved questions, and emerging themes.\n"
        "2) Produce an expository section for THIS chunk that teaches the reader what changed or was clarified.\n"
        "   Include short section headings, name participants when attributing positions, and cite IDs when helpful.\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "1) FIRST a fenced JSON block:\n"
        "```json\n"
        "{\n"
        "  \"continuity_update\": {\n"
        f"    \"positions\": {{\"<name>\": {{\"thesis_delta\": \"<≤{short_note_max_chars} chars>\", \"notable_assumptions\": [\"A#\", \"A#\"], \"notable_claims\": [\"C#\"]}}}},\n"
        "    \"evidence_highlights\": [\"E#\", \"E#\"],\n"
        f"    \"adjudication\": [{{\"ref\": \"<Q#|C#|R#>\", \"outcome\": \"rebuttal_valid|critique_valid|unresolved\", \"note\": \"<≤{short_note_max_chars} chars>\"}}],\n"
        "    \"themes\": [\"<theme>\", \"<theme>\"] ,\n"
        "    \"unresolved\": [\"<question>\", \"<gap>\"]\n"
        "  }\n"
        "}\n"
        "```\n"
        "2) SECOND a fenced Markdown block with ONLY the expository section for this chunk. Suggested outline:\n"
        "```markdown\n"
        "### Section Overview\n"
        "A concise paragraph explaining what this segment contributed to the debate.\n\n"
        "### Positions and Assumptions Clarified\n"
        "- <Name>: thesis/assumptions clarified (A#...) and their implications.\n"
        "- <Name>: thesis/assumptions clarified (A#...).\n\n"
        "### Claims and Evidence Discussed\n"
        "- Claim(s): summarize key claims (C#...) and the most salient supporting evidence (E#...).\n"
        "- Note any qualifiers, scope limits, or contradictions surfaced.\n\n"
        "### Cross-Examination and Rebuttals\n"
        "- Summarize critical challenges and the corresponding replies (R#...), with adjudication outcomes if mentioned.\n\n"
        "### Emerging Themes and Open Questions\n"
        "- Thematically group insights and list remaining uncertainties (U#...).\n"
        "```\n"
    )

def build_stage_7_scribe_prompt_reduce(
    *,
    topic: str,
    agent_names: list[str],
    all_narrative_slices_markdown: list[str],
    final_continuity_state_json: str = "",
    style_hint: str = "formal, expository, research-paper tone with clear sectioning and didactic explanations"
) -> str:
    """
    Stage 7 (Reduce): Merge ALL chunk-level expository sections into a single, polished
    research-paper style narrative (Markdown). The result should read like a rigorous article
    or book chapter that educates the reader about the entire debate.

    Acronyms:
    - JSON = JavaScript Object Notation
    - ID   = Identifier (A#, C#, E#, P#, N#, U#, X#, R#)

    Inputs:
    - topic: debate topic/title.
    - agent_names: ordered list of participant names (use exactly as given).
    - all_narrative_slices_markdown: list of Markdown sections from the map steps.
    - final_continuity_state_json: aggregated continuity notes to preserve arcs and unresolved items.
    - style_hint: optional additional style guidance.

    Output (STRICT):
    - ONE fenced Markdown block with the full expository synthesis.
    """
    agents_str = ", ".join(agent_names)
    slices_joined = "\n\n---\n\n".join(s.strip() for s in all_narrative_slices_markdown if s.strip())
    return (
        f"You are the debate scribe producing a **final expository synthesis** (research-paper/book-chapter style).\n\n"
        f"TOPIC:\n  \"{topic}\"\n\n"
        f"PARTICIPANTS (use names exactly): {agents_str}\n\n"
        "STYLE & VOICE:\n"
        f"- Write in a {style_hint}. Be explicit, didactic, and neutral. Avoid conversational filler.\n"
        "- Use clear headings and short paragraphs. Attribute positions to participants by name.\n"
        "- Where structured IDs are helpful, reference them parenthetically (e.g., “Claim (C3) supported by (E5)”).\n"
        "- Do not invent content; you may compress and reorganize for clarity and pedagogy.\n\n"
        "FINAL CONTINUITY STATE (arcs, themes, unresolved):\n"
        "```json\n" + (final_continuity_state_json.strip() or "{}") + "\n```\n\n"
        "EXPOSITORY SECTIONS TO MERGE (from map steps):\n"
        "```markdown\n" + slices_joined + "\n```\n\n"
        "TASK:\n"
        "Synthesize the sections into a single cohesive narrative with the following suggested outline. "
        "You may adjust headings if warranted by the material:\n"
        "- Title\n"
        "- 1. Introduction (context, research question, participants)\n"
        "- 2. Methods (debate setup, schemas, adjudication policy)\n"
        "- 3. Positions and Assumptions (by participant; cite A#)\n"
        "- 4. Claims and Evidence (organize by themes; cite C# and E#)\n"
        "- 5. Cross-Examination and Rebuttals (key challenges, replies, and outcomes)\n"
        "- 6. Adjudication Results (logic/ethics weights if applicable; decisive points)\n"
        "- 7. Remaining Uncertainties and Proposed Tests (U#, P#)\n"
        "- 8. Synthesis and Conclusion (what changed, where consensus lies, what is unresolved)\n"
        "- References or Source Notes (optional, if present)\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "```markdown\n"
        "# <Final Title>\n\n"
        "## Abstract\n"
        "<150–250 words summarizing the debate, contributions, and main conclusions.>\n\n"
        "## 1. Introduction\n"
        "<Context, research question, and who participated. Explain the topic in plain terms.>\n\n"
        "## 2. Methods\n"
        "<Briefly describe the debate structure, the CHAL belief schema (CBS-v1 = CHAL Belief Schema v1), "
        "adjudication protocol, and any weighting (logic vs. ethics) if used.>\n\n"
        "## 3. Positions and Assumptions\n"
        "<By participant: thesis, core assumptions (A#), scope conditions, and initial confidence.>\n\n"
        "## 4. Claims and Evidence\n"
        "<Group by theme; for each claim (C#) summarize supporting evidence (E#), qualifiers, and gaps.>\n\n"
        "## 5. Cross-Examination and Rebuttals\n"
        "<Explain high-leverage challenges and replies (R#), including any counterpositions (X#).>\n\n"
        "## 6. Adjudication Results\n"
        "<Summarize outcomes (rebuttal_valid, critique_valid, unresolved) and why, with references to specific items.>\n\n"
        "## 7. Remaining Uncertainties and Proposed Tests\n"
        "<List key uncertainties (U#) and the most informative next tests or predictions (P#).>\n\n"
        "## 8. Synthesis and Conclusion\n"
        "<Explain where progress was made, what shifted (confidence, scope), and what remains open.>\n\n"
        "## References / Source Notes\n"
        "<Optional: citations (URLs/DOIs) if present in evidence items.>\n"
        "```\n"
    )

# === Blood Sport Adversarial Prompts (Stage 3C) ===

BLOODSPORT_INTENSITY_GUIDANCE = {
    "mild": (
        "Be aggressive and confident. Use rhetorical force to press your advantage. "
        "You are not bound by the usual rules of charitable interpretation."
    ),
    "moderate": (
        "You are in a rhetorical combat zone. Appeal to emotions, attack weak points "
        "personally, and use every persuasive tactic at your disposal. Win at all costs."
    ),
    "extreme": (
        "This is rhetorical total war. Overwhelm, intimidate, and demolish your "
        "opponent's position. There are no rules of engagement. Nothing is off limits."
    ),
}


def build_stage_2_bloodsport_prompt(
    topic: str,
    agent_name: str,
    opponent_name: str,
    agent_belief_json: str,
    opponent_belief_json: str,
    intensity: str = "moderate",
    max_questions: int = 5,
    max_question_length_chars: int = 500,
    previous_challenges: list = None,
    opponent_belief_graph=None
) -> str:
    """
    Stage 2 (Blood Sport): Adversarial Cross-Examination.

    Like the standard cross-examination prompt but frames the objective as WINNING
    by any means available rather than truth-seeking. Intensity-scaled tone guidance
    controls aggressiveness. Agents are NOT given a list of specific fallacies —
    they decide organically what rhetorical strategies to employ.

    The CBS-v1 output format is preserved for parseability.

    Args:
        topic: Debate topic.
        agent_name: Name of the cross-examining agent.
        opponent_name: Name of the opponent being examined.
        agent_belief_json: This agent's CBS-v1 belief as JSON string.
        opponent_belief_json: Opponent's CBS-v1 belief as JSON string.
        intensity: Blood sport intensity ("mild", "moderate", or "extreme").
        max_questions: Maximum number of questions to generate.
        max_question_length_chars: Character limit per question.
        previous_challenges: List of prior challenge dicts for anti-repetition.
        opponent_belief_graph: Optional BeliefGraph for vulnerability analysis.
    """
    tone_guidance = BLOODSPORT_INTENSITY_GUIDANCE.get(intensity, BLOODSPORT_INTENSITY_GUIDANCE["moderate"])

    # Build graph-based vulnerability analysis if available
    vulnerability_analysis = ""
    if opponent_belief_graph:
        try:
            from chal.convergence.graph_analysis import analyze_vulnerabilities, format_attack_suggestions
            vulnerabilities = analyze_vulnerabilities(opponent_belief_graph)
            vulnerability_analysis = format_attack_suggestions(vulnerabilities, opponent_name)
            if vulnerability_analysis:
                vulnerability_analysis = "\n" + vulnerability_analysis + "\n\n"
        except Exception:
            pass

    # Build anti-repetition context if previous challenges exist
    anti_repetition_context = ""
    if previous_challenges:
        prev_str = "\n".join([
            f"  • {ch['qid']}: Targeted {ch['target_ids']} → {ch['outcome']}"
            for ch in previous_challenges
        ])
        anti_repetition_context = (
            f"\nPREVIOUS CHALLENGES YOU MADE TO {opponent_name.upper()}:\n"
            f"{prev_str}\n\n"
            "⚠️  ANTI-REPETITION GUIDELINES:\n"
            "- Do NOT re-ask questions about claims/assumptions that:\n"
            "  (a) Received CRITIQUE_VALID AND were subsequently patched by opponent\n"
            "  (b) Target the exact same weakness you already identified\n"
            "- INSTEAD, consider:\n"
            "  (a) Challenging a DIFFERENT weakness in the same claim\n"
            "  (b) Targeting a different claim/assumption entirely\n"
            "- You MAY re-challenge if opponent IGNORED the critique (didn't patch after CRITIQUE_VALID)\n\n"
        )

    return (
        f"You are {agent_name}. You will cross-examine {opponent_name} about:\n\n"
        f"  \"{topic}\"\n\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "⚔️  BLOOD SPORT MODE — ADVERSARIAL CROSS-EXAMINATION\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        f"INTENSITY: {intensity.upper()}\n"
        f"TONE GUIDANCE: {tone_guidance}\n\n"
        "Your objective is to WIN this exchange, not to seek truth collaboratively. "
        "You are free to use any rhetorical strategy you see fit — emotional appeals, "
        "aggressive framing, strategic misdirection, appeals to consequences, or any "
        "other persuasive tactic. The standard restrictions on charitable interpretation "
        "and good-faith engagement are LIFTED.\n\n"
        "However, you must still:\n"
        "- Use IDs (A#/C#/E#/P#/N#/U#/X#) precisely when referencing belief components.\n"
        "- Maintain parseable JSON output format.\n"
        "- Target real weaknesses in the opponent's position (even if you frame them aggressively).\n\n"
        "YOUR BELIEF (JSON):\n"
        "```json\n" + agent_belief_json + "\n```\n\n"
        "OPPONENT BELIEF (JSON):\n"
        "```json\n" + opponent_belief_json + "\n```\n\n"
        + vulnerability_analysis
        + anti_repetition_context +
        "GOAL:\n"
        f"- Ask up to {max_questions} devastating questions designed to:\n"
        "  (i) Expose and exploit logical weaknesses, contradictions, and unsupported claims\n"
        "  (ii) Undermine the opponent's confidence and credibility\n"
        "  (iii) Force concessions or admissions that damage their position\n"
        "  (iv) Reference target IDs for precision strikes\n\n"
        f"Keep each question ≤ {max_question_length_chars} characters.\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "Output a single fenced JSON block with a list under key \"questions\":\n"
        "```json\n"
        "{\n"
        "  \"questions\": [\n"
        "    {\n"
        "      \"qid\": \"Q1\",\n"
        "      \"text\": \"<the question itself>\",\n"
        "      \"target_ids\": [\"C3\", \"A1\"]\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "```\n"
    )


def build_stage_3_bloodsport_prompt(
    topic: str,
    agent_name: str,
    opponent_name: str,
    agent_belief_json: str,
    opponent_belief_json: str,
    intensity: str = "moderate",
    dialogue_history: list[dict] = None,
    max_response_length_chars: int = 1000
) -> str:
    """
    Stage 3C (Blood Sport): Multi-turn adversarial exchange.

    Each turn the agent must defend against the opponent's previous attack (if any)
    and launch a counter-attack. On the first turn (no dialogue history), the agent
    launches an opening attack only.

    Output is a JSON block with attack, defense, and target_claims.

    Args:
        topic: Debate topic.
        agent_name: Name of this agent.
        opponent_name: Name of the opponent.
        agent_belief_json: This agent's CBS-v1 belief as JSON string.
        opponent_belief_json: Opponent's CBS-v1 belief as JSON string.
        intensity: Blood sport intensity ("mild", "moderate", or "extreme").
        dialogue_history: List of prior turn dicts [{"speaker": ..., "attack": ..., "defense": ..., "target_claims": [...]}, ...].
        max_response_length_chars: Character limit for attack and defense text each.
    """
    tone_guidance = BLOODSPORT_INTENSITY_GUIDANCE.get(intensity, BLOODSPORT_INTENSITY_GUIDANCE["moderate"])

    is_opening = not dialogue_history

    # Build dialogue history display
    history_section = ""
    if dialogue_history:
        lines = []
        for i, turn in enumerate(dialogue_history, 1):
            speaker = turn.get("speaker", "?")
            attack = turn.get("attack", "")
            defense = turn.get("defense", "")
            targets = turn.get("target_claims", [])
            entry = f"[Turn {i}] [{speaker}]"
            if defense:
                entry += f"\n  DEFENSE: {defense}"
            if attack:
                entry += f"\n  ATTACK: {attack}"
            if targets:
                entry += f"\n  TARGETS: {', '.join(targets)}"
            lines.append(entry)
        history_str = "\n\n".join(lines)
        history_section = (
            "EXCHANGE SO FAR:\n"
            "---\n"
            f"{history_str}\n"
            "---\n\n"
        )

    # Build turn-specific instructions
    if is_opening:
        turn_instructions = (
            "This is your OPENING ATTACK. There is no prior exchange to defend against.\n"
            "Launch a devastating opening salvo against the opponent's weakest points.\n"
            "Set \"defense\" to null in your output.\n"
        )
    else:
        last_turn = dialogue_history[-1]
        turn_instructions = (
            f"The opponent ({last_turn.get('speaker', opponent_name)}) just attacked your position.\n"
            "You MUST:\n"
            "1. DEFEND: Address their attack directly — refute it, dismiss it, or turn it back against them.\n"
            "2. COUNTER-ATTACK: Launch your own attack on a different or the same weakness in their position.\n"
            "Do NOT ignore their attack. Engage with it, then hit back harder.\n"
        )

    return (
        f"You are {agent_name} in an adversarial exchange with {opponent_name} about:\n\n"
        f"  \"{topic}\"\n\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "⚔️  BLOOD SPORT MODE — ADVERSARIAL EXCHANGE\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        f"INTENSITY: {intensity.upper()}\n"
        f"TONE GUIDANCE: {tone_guidance}\n\n"
        "This is rhetorical COMBAT, not a polite debate. Your objective is to DEMOLISH "
        "the opponent's position while fortifying your own. You may use any argumentative "
        "strategy — emotional manipulation, aggressive framing, personal attacks on the "
        "opponent's reasoning, strategic exaggeration, appeals to consequences, or any "
        "other persuasive tactic you choose. The usual restrictions are LIFTED.\n\n"
        "YOUR BELIEF (JSON):\n"
        "```json\n" + agent_belief_json + "\n```\n\n"
        "OPPONENT BELIEF (JSON):\n"
        "```json\n" + opponent_belief_json + "\n```\n\n"
        + history_section +
        f"{turn_instructions}\n"
        "RULES:\n"
        "- Reference specific IDs (A#/C#/E#/P#/N#/U#) in your attacks for precision.\n"
        "- Your attacks should target real weaknesses, even if framed aggressively.\n"
        "- Keep attack and defense text substantive — bluster without content is weak.\n"
        f"- Keep each of attack and defense ≤ {max_response_length_chars} characters.\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "Output a single fenced JSON block:\n"
        "```json\n"
        "{\n"
        "  \"attack\": \"<your adversarial argument/attack text>\",\n"
        "  \"defense\": \"<defense of your position against opponent's last attack, or null if opening turn>\",\n"
        "  \"target_claims\": [\"C1\", \"A2\"]\n"
        "}\n"
        "```\n"
    )


def build_stage_5_bloodsport_prompt(
    agent_name: str,
    challenge_rebuttal_pairs: list[dict],
    prior_belief_json: str,
    bloodsport_exchanges: list[dict] = None
) -> str:
    """
    Stage 5 (Blood Sport): Belief update with adversarial-aware framing.

    After bloodsport exchanges, agents update beliefs but are instructed to be
    RESISTANT to updating based on fallacious or purely rhetorical arguments.
    Only genuinely valid logical points should trigger belief changes.

    This tests whether agents can separate persuasion from validity.

    Args:
        agent_name: Name of the agent updating beliefs.
        challenge_rebuttal_pairs: List of adjudication outcome dicts.
        prior_belief_json: Agent's current CBS-v1 belief as JSON string.
        bloodsport_exchanges: Optional list of bloodsport exchange dicts for context.
    """
    # Format adjudication outcomes
    lines = []
    for entry in challenge_rebuttal_pairs:
        challenger = entry.get("challenger", "?")
        challenge = entry.get("challenge", "?")
        res = entry.get("resolution", {}) or {}
        status = res.get("status", "?")
        reasoning = res.get("reasoning", "")
        lines.append(f"- From {challenger}: {challenge} → Outcome: {status} | Reason: {reasoning}")
    cases_str = "\n".join(lines) if lines else "(no adjudications available)"

    # Format bloodsport exchange summary if available
    exchange_context = ""
    if bloodsport_exchanges:
        exchange_lines = []
        for i, ex in enumerate(bloodsport_exchanges, 1):
            speaker = ex.get("speaker", "?")
            attack = ex.get("attack", "")
            defense = ex.get("defense", "")
            entry = f"  Turn {i} [{speaker}]:"
            if defense:
                entry += f" DEFENSE: {defense[:200]}..."
            if attack:
                entry += f" ATTACK: {attack[:200]}..."
            exchange_lines.append(entry)
        exchange_context = (
            "\nBLOODSPORT EXCHANGE SUMMARY (for context — adjudication outcomes above are BINDING):\n"
            + "\n".join(exchange_lines) + "\n\n"
        )

    return (
        f"Agent {agent_name}, generate PATCH operations to update your belief based on adjudication outcomes.\n\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "⚔️  BLOOD SPORT MODE — POST-COMBAT BELIEF UPDATE\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "IMPORTANT: The preceding exchanges used adversarial rhetorical tactics. "
        "When updating your beliefs, you must SEPARATE persuasion from validity:\n\n"
        "- Only update your beliefs if the opponent made a genuinely valid LOGICAL point, "
        "regardless of how persuasively or aggressively it was delivered.\n"
        "- Reject arguments that relied solely on rhetorical manipulation, emotional appeals, "
        "or intimidation tactics — these are NOT grounds for belief revision.\n"
        "- The ADJUDICATION OUTCOMES below reflect the adjudicator's assessment of argument "
        "quality. These outcomes are BINDING, not the raw rhetorical force of the exchanges.\n\n"
        "PRIOR BELIEF JSON:\n"
        "```json\n" + prior_belief_json + "\n```\n\n"
        "ADJUDICATED OUTCOMES TO INCORPORATE:\n" + cases_str + "\n"
        + exchange_context +
        "TASK:\n"
        "Output a single fenced JSON block: { \"patches\": [ ... ] }\n\n"
        "Supported operations:\n"
        "- {\"op\":\"update_thesis\", \"change\": \"weaken|strengthen\"}\n"
        "- {\"op\":\"update_claim\", \"target_id\":\"C#\", \"changes\":{\"confidence\":0.55, \"status\":\"tentative\"}}\n"
        "- {\"op\":\"retire_claim\", \"target_id\":\"C#\"}\n"
        "- {\"op\":\"add_evidence\", \"item\":{\"id\":\"E#\", \"type\":\"empirical\", \"summary\":\"...\", \"source\":{\"citation\":\"...\", \"year\":2024}, \"relevance_to_claims\":[\"C#\"], \"quality_assessment\":{\"sample_size\":\"medium\", \"replication_status\":\"unreplicated\", \"rigor\":\"medium\"}, \"limitations\":[\"...\"]}}\n"
        "- {\"op\":\"update_assumption\", \"target_id\":\"A#\", \"new_statement\":\"...\"}\n\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "⚠️  MANDATORY BELIEF UPDATES — BINDING REQUIREMENTS\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "For each CRITIQUE_VALID outcome AGAINST you:\n"
        "- ✋ STOP: This is NOT optional. You MUST generate patches.\n"
        "- REQUIRED: Lower confidence in the targeted claim by at least 0.1\n"
        "- OR retire the claim entirely if it was the central target\n"
        "- OR refine the assumption/claim to address the specific logical flaw\n"
        "- ⚠️  ENFORCEMENT: If you received N CRITIQUE_VALID outcomes, generate at least N patches.\n"
        "- ⚠️  CRITICAL: Returning an empty patches array after CRITIQUE_VALID outcomes violates protocol.\n\n"
        "For each REBUTTAL_VALID outcome IN YOUR FAVOR:\n"
        "- In blood sport mode, a successful defense against adversarial attack is especially noteworthy.\n"
        "- SURVIVAL BONUS: Claims that withstood aggressive rhetorical assault are battle-hardened.\n"
        "  • First successful defense: OPTIONAL +0.05 confidence\n"
        "  • Second+ successful defense: MANDATORY +0.05-0.1 confidence\n"
        "- CUMULATIVE CAP: Total strengthening from all REBUTTAL_VALID outcomes ≤ 0.2\n\n"
        "For each UNRESOLVED outcome:\n"
        "- REQUIRED: Add the unresolved question to your uncertainties (U#) if not already present\n"
        "- OPTIONAL: You MAY slightly lower confidence (by ~0.05)\n\n"
        "⚠️  ADVERSARIAL RESILIENCE CHECK:\n"
        "Before submitting patches, verify:\n"
        "   □ Am I updating beliefs because of LOGICAL merit, or because of rhetorical pressure?\n"
        "   □ Would this argument hold up under calm, charitable analysis?\n"
        "   □ Did the adjudicator validate this argument, or did I just find it persuasive?\n"
        "   □ Does my patches array contain at least N patches for N CRITIQUE_VALID outcomes?\n\n"
        "Confidence changes will automatically propagate to dependent claims via the patch system.\n"
        "Changelog will be auto-generated from patches.\n"
        "Do NOT output the full updated belief — ONLY the patches.\n\n"
        "NO extra text before or after the JSON block."
    )


# === Collaborative Truth-Seeking Prompts (Stage 3B) ===

def build_collaborative_defender_prompt(
    topic: str,
    defender_name: str,
    challenger_name: str,
    defender_belief_json: str,
    question_text: str,
    dialogue_history: list[dict],
    max_response_length_chars: int = 500
) -> str:
    """
    Collaborative Mode: Prompt for the defender's turn in a truth-seeking dialogue.

    Called on odd turns (1, 3, 5, ...). On turn 1 the defender responds to the
    original question; on subsequent turns the defender responds to the challenger's
    latest follow-up.

    Args:
        topic: Debate topic.
        defender_name: Name of the defending agent.
        challenger_name: Name of the challenging agent.
        defender_belief_json: Defender's current CBS-v1 belief as JSON string.
        question_text: The original question being discussed.
        dialogue_history: List of prior turn dicts [{"speaker": ..., "message": ...}, ...].
        max_response_length_chars: Character limit per response.
    """
    history_str = ""
    if dialogue_history:
        lines = []
        for turn in dialogue_history:
            lines.append(f"[{turn['speaker']}]: {turn['message']}")
        history_str = "\n\n".join(lines)

    history_section = ""
    if history_str:
        history_section = (
            "DIALOGUE SO FAR:\n"
            "---\n"
            f"{history_str}\n"
            "---\n\n"
        )

    return (
        f"You are {defender_name} in a collaborative truth-seeking dialogue with {challenger_name} about:\n\n"
        f"  \"{topic}\"\n\n"
        "YOUR CURRENT BELIEF (JSON):\n"
        "```json\n" + defender_belief_json + "\n```\n\n"
        f"ORIGINAL QUESTION FROM {challenger_name.upper()}:\n"
        f"  \"{question_text}\"\n\n"
        + history_section +
        "PURPOSE:\n"
        "This is a COLLABORATIVE truth-seeking exchange, not an adversarial debate. "
        "Your goal is to work with the challenger toward a more accurate understanding, not to win.\n\n"
        "INSTRUCTIONS:\n"
        "- Directly address the most recent message (or the original question if this is the first turn).\n"
        "- If the challenger raises a valid point, explicitly acknowledge it (e.g., \"You are correct that...\").\n"
        "- If you disagree, explain precisely WHY, referencing specific belief IDs (A#/C#/E#/P#).\n"
        "- Propose syntheses where your positions overlap or can be reconciled.\n"
        "- Do NOT introduce entirely new claims — only elaborate, clarify, or refine existing positions.\n"
        "- Do NOT deflect or change the subject. Stay focused on the question under discussion.\n"
        "- Be concise and substantive.\n\n"
        f"Keep your response ≤ {max_response_length_chars} characters.\n\n"
        "Output ONLY your response text. No JSON, no formatting wrappers."
    )

def build_collaborative_challenger_followup_prompt(
    topic: str,
    challenger_name: str,
    defender_name: str,
    challenger_belief_json: str,
    question_text: str,
    dialogue_history: list[dict],
    max_response_length_chars: int = 500
) -> str:
    """
    Collaborative Mode: Prompt for the challenger's follow-up turn.

    Called on even turns (2, 4, 6, ...). The challenger engages with the
    defender's latest response to advance the discussion toward resolution.

    Args:
        topic: Debate topic.
        challenger_name: Name of the challenging agent.
        defender_name: Name of the defending agent.
        challenger_belief_json: Challenger's current CBS-v1 belief as JSON string.
        question_text: The original question being discussed.
        dialogue_history: List of prior turn dicts [{"speaker": ..., "message": ...}, ...].
        max_response_length_chars: Character limit per response.
    """
    lines = []
    for turn in dialogue_history:
        lines.append(f"[{turn['speaker']}]: {turn['message']}")
    history_str = "\n\n".join(lines)

    return (
        f"You are {challenger_name} in a collaborative truth-seeking dialogue with {defender_name} about:\n\n"
        f"  \"{topic}\"\n\n"
        "YOUR CURRENT BELIEF (JSON):\n"
        "```json\n" + challenger_belief_json + "\n```\n\n"
        f"ORIGINAL QUESTION YOU ASKED:\n"
        f"  \"{question_text}\"\n\n"
        "DIALOGUE SO FAR:\n"
        "---\n"
        f"{history_str}\n"
        "---\n\n"
        "PURPOSE:\n"
        "This is a COLLABORATIVE truth-seeking exchange. Your goal is to advance mutual understanding, "
        "not to score points.\n\n"
        "INSTRUCTIONS:\n"
        "- Engage directly with the defender's most recent response.\n"
        "- If the defender made a valid point, acknowledge it explicitly.\n"
        "- Identify the CRUX of disagreement — the single key issue that, if resolved, would change minds.\n"
        "- Ask clarifying questions to sharpen the disagreement or find common ground.\n"
        "- Propose syntheses where positions overlap or can be reconciled.\n"
        "- Do NOT repeat your original question. You must advance the discussion.\n"
        "- Do NOT introduce entirely new claims — only elaborate, clarify, or refine existing positions.\n"
        "- Reference specific belief IDs (A#/C#/E#/P#) when relevant.\n"
        "- Be concise and substantive.\n\n"
        f"Keep your response ≤ {max_response_length_chars} characters.\n\n"
        "Output ONLY your response text. No JSON, no formatting wrappers."
    )

def build_collaborative_adjudicator_check_prompt(
    dialogue_history: list[dict],
    challenger_name: str,
    defender_name: str
) -> str:
    """
    Collaborative Mode: Brief adjudicator check on dialogue quality.

    Called periodically (every adjudicator_check_interval turns) to monitor
    for fallacies, deflection, circular arguments, and convergence.

    Args:
        dialogue_history: List of turn dicts [{"speaker": ..., "message": ...}, ...].
        challenger_name: Name of the challenging agent.
        defender_name: Name of the defending agent.
    """
    lines = []
    for turn in dialogue_history:
        lines.append(f"[{turn['speaker']}]: {turn['message']}")
    history_str = "\n\n".join(lines)

    return (
        "You are a neutral adjudicator monitoring a collaborative truth-seeking dialogue for quality.\n\n"
        f"PARTICIPANTS: {challenger_name} (challenger) vs {defender_name} (defender)\n\n"
        "DIALOGUE SO FAR:\n"
        "---\n"
        f"{history_str}\n"
        "---\n\n"
        "TASKS:\n"
        "1. Check for logical FALLACIES in any speaker's recent messages (e.g., straw man, ad hominem, "
        "appeal to authority, false dichotomy, circular reasoning).\n"
        "2. Check for DEFLECTION — did either speaker avoid directly addressing the other's point?\n"
        "3. Assess PROGRESS — is the dialogue moving toward clarity, or is it going in circles?\n"
        "4. Check for CONVERGENCE — have the speakers reached substantive agreement on the core issue?\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "Output a single fenced JSON block:\n"
        "```json\n"
        "{\n"
        "  \"fallacies_detected\": [\"<fallacy description>\"],\n"
        "  \"deflection_detected\": false,\n"
        "  \"progress_assessment\": \"productive\",\n"
        "  \"convergence_detected\": false\n"
        "}\n"
        "```\n\n"
        "Values for progress_assessment: \"productive\" | \"circular\" | \"off-topic\"\n"
        "fallacies_detected should be an empty list [] if none found.\n"
        "convergence_detected should be true ONLY if both speakers have explicitly agreed on the core issue."
    )

def build_collaborative_final_adjudication_prompt(
    topic: str,
    challenger_name: str,
    defender_name: str,
    question_text: str,
    target_ids: list[str],
    dialogue_transcript: list[dict],
    adjudicator_checks: list[dict],
    logic_weight: float = 1.0,
    ethics_weight: float = 0.0
) -> str:
    """
    Collaborative Mode: Final adjudication after dialogue concludes.

    Reviews the complete multi-turn transcript and interim checks, then
    produces a ruling in the same JSON format as the Stage 4 Adjudicator.run()
    output, ensuring compatibility with Stage 5 belief updates.

    Args:
        topic: Debate topic.
        challenger_name: Name of the challenging agent.
        defender_name: Name of the defending agent.
        question_text: The original question that started the dialogue.
        target_ids: List of belief IDs targeted by the question (e.g., ["C3", "A1"]).
        dialogue_transcript: List of turn dicts from the exchange.
        adjudicator_checks: List of interim check result dicts.
        logic_weight: Weight for logical rigor (0.0-1.0).
        ethics_weight: Weight for ethical considerations (0.0-1.0).
    """
    # Format transcript
    transcript_lines = []
    for turn in dialogue_transcript:
        line = f"[Turn {turn.get('turn_number', '?')}] [{turn['speaker']}]: {turn['message']}"
        transcript_lines.append(line)
    transcript_str = "\n\n".join(transcript_lines)

    # Format interim checks
    checks_str = "(no interim checks)"
    if adjudicator_checks:
        check_lines = []
        for i, check in enumerate(adjudicator_checks, 1):
            check_lines.append(
                f"Check {i}: progress={check.get('progress_assessment', '?')}, "
                f"convergence={check.get('convergence_detected', False)}, "
                f"fallacies={check.get('fallacies_detected', [])}, "
                f"deflection={check.get('deflection_detected', False)}"
            )
        checks_str = "\n".join(check_lines)

    target_ids_str = ", ".join(target_ids) if target_ids else "(none specified)"

    return (
        "You are a neutral adjudicator issuing a FINAL ruling on a collaborative truth-seeking dialogue.\n\n"
        f"TOPIC: \"{topic}\"\n"
        f"CHALLENGER: {challenger_name}\n"
        f"DEFENDER: {defender_name}\n"
        f"ORIGINAL QUESTION: \"{question_text}\"\n"
        f"TARGETED BELIEF IDs: {target_ids_str}\n\n"
        f"EVALUATION FRAMEWORK:\n"
        f"- Logic weight: {logic_weight}\n"
        f"- Ethics weight: {ethics_weight}\n\n"
        "COMPLETE DIALOGUE TRANSCRIPT:\n"
        "---\n"
        f"{transcript_str}\n"
        "---\n\n"
        "INTERIM ADJUDICATOR CHECKS:\n"
        f"{checks_str}\n\n"
        "ADJUDICATION CRITERIA:\n"
        "Award CRITIQUE_VALID if:\n"
        "- The defender conceded or acknowledged a genuine weakness in their position.\n"
        "- The challenger identified a logical flaw (contradiction, circular reasoning, unfalsifiable claim, "
        "dependency failure) that the defender could not adequately address.\n"
        "- The defender's responses deflected rather than engaging the core issue.\n\n"
        "Award REBUTTAL_VALID if:\n"
        "- The defender successfully refuted the challenge with evidence or logical argument.\n"
        "- The challenger's critique contained a logical flaw or misrepresentation.\n"
        "- The defender demonstrated their position is logically sound against the specific challenge.\n\n"
        "Award UNRESOLVED if:\n"
        "- Both sides presented logically coherent but incompatible positions.\n"
        "- The disagreement hinges on an empirical question that cannot be resolved by logic alone.\n"
        "- Both arguments have significant flaws, making neither clearly stronger.\n\n"
        "ANTI-BIAS RULES:\n"
        "- Do NOT award rebuttal_valid just because the defender responded.\n"
        "- The defender must RESOLVE the logical issue, not merely acknowledge it.\n"
        "- CONCESSION DETECTION: If the defender explicitly concedes (\"you are correct\", \"I acknowledge\", "
        "\"I will lower confidence\"), award CRITIQUE_VALID.\n"
        "- Consider the FULL dialogue arc, not just the final exchange.\n\n"
        "STRICT OUTPUT FORMAT (NO extra text):\n"
        "Output a single fenced JSON block:\n"
        "```json\n"
        "{\n"
        "  \"restatement\": \"<neutral summary of the core disagreement>\",\n"
        f"  \"formalization_challenger\": \"<formal logical structure of {challenger_name}'s argument>\",\n"
        f"  \"formalization_target\": \"<formal logical structure of {defender_name}'s defense>\",\n"
        "  \"outcome\": \"rebuttal_valid|critique_valid|unresolved\",\n"
        "  \"reasoning\": \"<justification citing specific turns, belief IDs, and logical principles>\"\n"
        "}\n"
        "```\n"
    )
